//: https://github.com/jsdom/cssstyle/issues/182
packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
