packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
catalog:
  '@tanstack/devtools-ui': ^0.3.1
  '@tanstack/solid-store': ^0.7.3
  clsx: ^2.1.1
  dayjs: ^1.11.13
  goober: ^2.1.16
  solid-js: ^1.9.7
  vite: ^7.0.6
  vite-plugin-solid: ^2.11.6
